name: Gosec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Gosec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.0']
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
